name: Lint and Test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      
jobs:      
  lint_and_test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo apt update
          sudo apt install python3
          python -m pip install --upgrade pip
        
      - name: Set up Python
        uses: actions/setup-python@v1
        
      - name: Install flake8
        run: |
          pip install flake8 
          
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
